# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/go/src/github.com/vishwanathj/JSON-Parameterized-Data-Validator
    steps:
      - checkout
      #- run: make docker-gosec
      - run: make docker-lint
      - run: make docker-unit