version: '3.3'
services:
  vnfdservice:
    environment:
      MONGO_IP: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo
    #command: vnfdservice -ip mongo
    command: vnfdservice
  mongo:
    image: mongo:4-xenial
    ports:
      - "27017:27017"
  jmeter:
    image: justb4/jmeter
    depends_on:
      - vnfdservice
    volumes:
      - ../../test/testdata/jmeter/:/tmp/jmeter/
    command: -n -t /tmp/jmeter/PostVNFDRuntimeCSV.jmx