version: '3.3'
services:
  vnfdservice:
    image: vnfdservice:test
    build:
      context: ../../
      dockerfile: build/package/Dockerfile_test
    environment:
      - RESULTS_DIR=/go/src/github.com/vishwanathj/protovnfdparser/results
    volumes:
      - ../../results:/go/src/github.com/vishwanathj/protovnfdparser/results
    working_dir: /go/src/github.com/vishwanathj/protovnfdparser
    #https://stackoverflow.com/questions/51022134/docker-compose-cant-print-environment-variable-in-docker-container
    #https://docs.docker.com/compose/compose-file/#variable-substitution
    command: bash -c "go test ./... -coverprofile=$$RESULTS_DIR/coverage_unit.out -tags=unit
      && go tool cover -html=$$RESULTS_DIR/coverage_unit.out -o $$RESULTS_DIR/coverage_unit.html"